### ISSUE TITLE
ocaml_intrinsics.v0.15~preview.126.02+18 fails to build on Raspberry PI 4

### ISSUE THREAD

**Issue by jkilburg** [janestreet/ocaml_intrinsics#3]
Building on an RPI4 I saw the following error:

```
# (cd _build/default/src && /usr/bin/arm-linux-gnueabihf-gcc -O2 -fno-strict-aliasing -fwrapv -fPIC -D_FI
LE_OFFSET_BITS=64 -D_REENTRANT -O2 -fno-strict-aliasing -fwrapv -fPIC -g -I /usr/lib/ocaml -o crc_stubs.o
 -c crc_stubs.c)                                                                                         
# crc_stubs.c: In function ‘crc32’:                                                                      
# crc_stubs.c:27:2: error: #error "Target not supported"                                                 
#    27 | #error "Target not supported"                                                                  
#       |  ^~~~~                                                                                         
```

System details:
Raspbian based on Debian 11.2
Compiler 4.11.1 which is the version provided with the default switch with the system packaged opam 2.0.8

I made a tweak to the discover program to add a gcc flag which seems to expose the needed bits. I was able to install async after making the change. See my commit to [jkilburg/ocaml_intrinsics](https://github.com/jkilburg/ocaml_intrinsics).

**Comment by gretay-js** [comment]
Thank you for the report and the proposed fix, I'll get a version of it merged in.  
It should also work without the patch if the default C compiler used by opam is configured with "-march=armv8-a+crc", (i.e., gcc on the PATH when opam switch is created or specified like [this]( https://discuss.ocaml.org/t/opam-switch-create-and-gcc10/5864/7)).
If the default compiler is configured for example with -march=armv8.1-a+simd, it will already have __ARM_FEATURE_CRC32 on because crc32 extension is not optional from armv8.1-a. Setting -march=armv8-a+crc explicitly will turn off other extensions that may be available, such as +simd in this example. There is no way to turn on one extension separately from -march, as far as I know, so your patch is probably the best solution for now, as we don't yet use anything that requires other optional extensions or newer instructions like +sb in this library. If later on other extensions are needed, we can rearrange the library to use -march=armv8.1-a+simd only when compiling `crc_stubs.c`.

**Comment by jkilburg** [comment]
Thank you thinking about how to handle this!

I had not considered an opam change which sounds interesting. It might be kind of cool to have opam switches like "jane-0.15...+4.12.1+armv8...", "jane-0.16...+4.13.1+armv8...", etc though it would be very easy to go overboard with it.
